// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBla98Jn0U3Coj6-5kA2cRWCmsA-whnPyU',
    appId: '1:89007665756:web:b6ae4933251e8000d9ac99',
    messagingSenderId: '89007665756',
    projectId: 'transferet-relocations',
    authDomain: 'transferet-relocations.firebaseapp.com',
    databaseURL: 'https://transferet-relocations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transferet-relocations.appspot.com',
    measurementId: 'G-XJ0XHGGWR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrywcaeqjZB8L8GvV_kCXCBekz66MMW1E',
    appId: '1:89007665756:android:3bbb439147dcd285d9ac99',
    messagingSenderId: '89007665756',
    projectId: 'transferet-relocations',
    databaseURL: 'https://transferet-relocations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transferet-relocations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAI531cooCAIErBadGoYZ0uuMMSZbUVik',
    appId: '1:89007665756:ios:b95b8d68bc063667d9ac99',
    messagingSenderId: '89007665756',
    projectId: 'transferet-relocations',
    databaseURL: 'https://transferet-relocations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transferet-relocations.appspot.com',
    iosClientId: '89007665756-c7fp58mftp6qeplt7ivj50qnlhkvbk8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.transferet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAI531cooCAIErBadGoYZ0uuMMSZbUVik',
    appId: '1:89007665756:ios:f0ec75a3a24217a9d9ac99',
    messagingSenderId: '89007665756',
    projectId: 'transferet-relocations',
    databaseURL: 'https://transferet-relocations-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transferet-relocations.appspot.com',
    iosClientId: '89007665756-ehjs26hnr4d784i77g3t5n4h39l49g7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.transferet.RunnerTests',
  );
}
